// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY1bcCCSBGVcBgwWzRmQp6tPD6-VDycJc',
    appId: '1:333002007969:web:a62bce954c25ce436317e0',
    messagingSenderId: '333002007969',
    projectId: 'heart-nagaland',
    authDomain: 'heart-nagaland.firebaseapp.com',
    storageBucket: 'heart-nagaland.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY1bcCCSBGVcBgwWzRmQp6tPD6-VDycJc',
    appId: '1:333002007969:android:171f676b4ac62a686317e0',
    messagingSenderId: '333002007969',
    projectId: 'heart-nagaland',
    storageBucket: 'heart-nagaland.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY1bcCCSBGVcBgwWzRmQp6tPD6-VDycJc',
    appId: '1:333002007969:ios:a42ed18de50bcb636317e0',
    messagingSenderId: '333002007969',
    projectId: 'heart-nagaland',
    storageBucket: 'heart-nagaland.firebasestorage.app',
    iosBundleId: 'com.nititechnologies.heart.heartNagalandFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY1bcCCSBGVcBgwWzRmQp6tPD6-VDycJc',
    appId: '1:333002007969:ios:a42ed18de50bcb636317e0',
    messagingSenderId: '333002007969',
    projectId: 'heart-nagaland',
    storageBucket: 'heart-nagaland.firebasestorage.app',
    iosBundleId: 'com.nititechnologies.heart.heartNagalandFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY1bcCCSBGVcBgwWzRmQp6tPD6-VDycJc',
    appId: '1:333002007969:web:a62bce954c25ce436317e0',
    messagingSenderId: '333002007969',
    projectId: 'heart-nagaland',
    authDomain: 'heart-nagaland.firebaseapp.com',
    storageBucket: 'heart-nagaland.firebasestorage.app',
  );
}
